language: en-US
reviews:
  profile: balanced
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!node_modules/"
    - "!**/*.map"
tools:
  eslint:
    enabled: true
  gitleaks:
    enabled: true
